import { Router } from "express";
import authRoutes from "./modules/auth/routes/auth.routes";
import lawFirmRoutes from "./modules/lawfirm/routes/lawfirm.routes";
import courtRoutes from "./modules/court/routes/court.routes";
import userRoutes from "./modules/user/routes/user.routes";
import clientRoutes from "./modules/client/routes/client.routes";
import caseRoutes from "./modules/case/routes/case.routes";
import hearingRoutes from "./modules/hearing/routes/hearing.routes";
import documentRoutes from "./modules/document/routes/document.routes";
import clientPortalRoutes from "./modules/client-portal/routes/client-portal.routes";
import reportRoutes from "./modules/report/routes/report.routes";
import notificationRoutes from "./modules/notification/routes/notification.routes";
import auditLogRoutes from "./modules/audit-log/routes/audit-log.routes";
import libraryRoutes from "./modules/library/routes/library.routes";
import companyStaffRoutes from "./modules/company-staff/routes/company-staff.routes";
import pushRoutes from "./modules/push/routes/push.routes";
import subscriptionRoutes from "./modules/subscription/routes/subscription.routes";
import documentTemplateRoutes from "./modules/document-template/routes/document-template.routes";
import subjectRoutes from "./modules/subject/routes/subject.routes";
import mcqRoutes from "./modules/mcq/routes/mcq.routes";
import mockTestRoutes from "./modules/mock-test/routes/mock-test.routes";
import bookmarkRoutes from "./modules/bookmark/bookmark.routes";
import studyProgressRoutes from "./modules/study-progress/study-progress.routes";
import courseRoutes from "./modules/course/routes/course.routes";
import liveClassRoutes from "./modules/live-class/routes/live-class.routes";
import rolePermissionRoutes from "./modules/role-permission/role-permission.routes";
import tenantRoleRoutes from "./modules/tenant-role/tenant-role.routes";
import feedbackRoutes from "./modules/feedback/feedback.routes";
import testSectionRoutes from "./modules/test-section/test-section.routes";
import writingSubmissionRoutes from "./modules/writing-submission/writing-submission.routes";
import chatbotRoutes from "./modules/chatbot/chatbot.routes";
import contentGeneratorRoutes from "./modules/content-generator/content-generator.routes";
import paymentRoutes from "./modules/payment/payment.routes";
import flashcardRoutes from "./modules/flashcard/routes/flashcard.routes";
import precedentRoutes from "./modules/precedent/routes/precedent.routes";
import userPermissionRoutes from "./modules/user-permission/routes/user-permission.routes";
import speakingRoutes from "./modules/speaking/routes/speaking.routes";
import usageLimitRoutes from "./modules/usage-limit/routes/usage-limit.routes";
import practiceSessionRoutes from "./modules/practice-session/routes/practice-session.routes";
import institutionFeeRoutes from "./modules/institution-fee/routes/institution-fee.routes";
import emailVerificationRoutes from "./modules/email-verification/routes/email-verification.routes";
import staffPayrollRoutes from "./modules/staff-payroll/routes/staff-payroll.routes";

const router = Router();

// Health check (no auth required) — useful for Docker/uptime checks later
router.get("/health", (req, res) => {
  res.status(200).json({ success: true, message: "NyayaOne API is running", timestamp: new Date().toISOString() });
});

router.use("/auth", authRoutes);
router.use("/law-firms", lawFirmRoutes);
router.use("/courts", courtRoutes);
router.use("/users", userRoutes);
router.use("/clients", clientRoutes);
router.use("/cases", caseRoutes);
router.use("/hearings", hearingRoutes);
router.use("/documents", documentRoutes);
router.use("/client-portal", clientPortalRoutes);
router.use("/reports", reportRoutes);
router.use("/notifications", notificationRoutes);
router.use("/audit-logs", auditLogRoutes);
router.use("/library", libraryRoutes);
router.use("/company-staff", companyStaffRoutes);
router.use("/push", pushRoutes);
router.use("/subscriptions", subscriptionRoutes);
router.use("/document-templates", documentTemplateRoutes);

// Phase 2 — Student Learning Platform
router.use("/subjects", subjectRoutes);
router.use("/mcq", mcqRoutes);
router.use("/mock-tests", mockTestRoutes);
router.use("/bookmarks", bookmarkRoutes);
router.use("/flashcards", flashcardRoutes);
router.use("/precedents", precedentRoutes);
router.use("/user-permissions", userPermissionRoutes);
router.use("/speaking", speakingRoutes);
router.use("/usage-limits", usageLimitRoutes);
router.use("/practice-sessions", practiceSessionRoutes);
router.use("/institution-fee", institutionFeeRoutes);
router.use("/email-verification", emailVerificationRoutes);
router.use("/staff-payroll", staffPayrollRoutes);
router.use("/study-progress", studyProgressRoutes);
router.use("/courses", courseRoutes);
router.use("/live-classes", liveClassRoutes);
router.use("/admin", rolePermissionRoutes);
router.use("/tenant", tenantRoleRoutes);
router.use("/feedback", feedbackRoutes);
router.use("/test-sections", testSectionRoutes);
router.use("/writing-submissions", writingSubmissionRoutes);
router.use("/chatbot", chatbotRoutes);
router.use("/content-generator", contentGeneratorRoutes);
router.use("/payment", paymentRoutes);

export default router;
